-- ============================================================
-- AIOS — Initial Schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- DEPARTMENTS (static reference data)
create table if not exists public.departments (
  id text primary key,
  display_name text not null,
  description text,
  icon text,
  color text,
  system_prompt text,
  model text default 'claude-sonnet-4-6',
  is_active boolean default true,
  config jsonb default '{}',
  created_at timestamptz default now()
);

-- CONVERSATIONS (chat threads per department)
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  dept_id text not null references departments(id),
  title text,
  thread_key text unique,
  is_pinned boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_conversations_dept on conversations(dept_id);
create index if not exists idx_conversations_updated on conversations(updated_at desc);

-- MESSAGES
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  metadata jsonb default '{}',
  created_at timestamptz default now()
);

create index if not exists idx_messages_conversation on messages(conversation_id, created_at);

-- AGENT_RUNS (every Claude API call logged)
create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  dept_id text not null references departments(id),
  conversation_id uuid references conversations(id),
  prompt_preview text,
  response_preview text,
  model text not null,
  input_tokens int default 0,
  output_tokens int default 0,
  cost_usd numeric(8,6) default 0,
  duration_ms int default 0,
  status text default 'running' check (status in ('running', 'completed', 'failed')),
  error text,
  metadata jsonb default '{}',
  started_at timestamptz default now(),
  completed_at timestamptz
);

create index if not exists idx_agent_runs_dept on agent_runs(dept_id, started_at desc);
create index if not exists idx_agent_runs_status on agent_runs(status) where status = 'running';

-- PROJECTS
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  dept_id text references departments(id),
  status text default 'inbox' check (status in ('inbox', 'in_progress', 'completed', 'archived')),
  description text,
  agent_run_id uuid references agent_runs(id),
  conversation_id uuid references conversations(id),
  notion_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  completed_at timestamptz
);

create index if not exists idx_projects_status on projects(status);
create index if not exists idx_projects_dept on projects(dept_id);

-- TASKS
create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references projects(id) on delete cascade,
  title text not null,
  status text default 'pending' check (status in ('pending', 'in_progress', 'completed')),
  assignee_type text default 'oscar' check (assignee_type in ('agent', 'oscar')),
  priority text default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  category text,
  due_date date,
  completed_at timestamptz,
  notion_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  sort_order int default 0
);

create index if not exists idx_tasks_project on tasks(project_id);
create index if not exists idx_tasks_status on tasks(status) where status != 'completed';

-- DOCUMENTS (drafts generated by agents, replaces Slack Canvas)
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references projects(id) on delete set null,
  conversation_id uuid references conversations(id),
  title text not null,
  content_md text not null default '',
  dept_id text references departments(id),
  status text default 'draft' check (status in ('draft', 'approved', 'executed', 'archived')),
  approved_at timestamptz,
  executed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- DOCUMENT_VERSIONS
create table if not exists public.document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  content_md text not null,
  version_number int not null,
  change_summary text,
  changed_by text default 'user',
  created_at timestamptz default now()
);

create index if not exists idx_doc_versions on document_versions(document_id, version_number desc);

-- CONNECTORS
create table if not exists public.connectors (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  display_name text not null,
  config jsonb default '{}',
  status text default 'disconnected' check (status in ('connected', 'disconnected', 'error')),
  last_sync_at timestamptz,
  error_message text,
  created_at timestamptz default now()
);

-- NOTIFICATIONS
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text,
  type text default 'info' check (type in ('info', 'success', 'warning', 'error')),
  source_dept text references departments(id),
  link_to text,
  is_read boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_notifications_unread on notifications(is_read, created_at desc)
  where is_read = false;

-- BRIEFS
create table if not exists public.briefs (
  id uuid primary key default gen_random_uuid(),
  type text default 'daily' check (type in ('daily', 'weekly')),
  content_md text not null,
  dept_summaries jsonb default '{}',
  date date not null default current_date,
  created_at timestamptz default now()
);

-- ============================================================
-- SEED DATA — Departments
-- ============================================================
insert into public.departments (id, display_name, description, icon, color, model) values
  ('orchestrator', 'Orquestador', 'Router central de tareas', '🧠', '#8B5CF6', 'claude-haiku-4-5-20251001'),
  ('cmo', 'CMO', 'Marketing y contenido', '📣', '#EC4899', 'claude-sonnet-4-6'),
  ('sdr', 'SDR', 'Captación y leads', '🎯', '#F59E0B', 'claude-sonnet-4-6'),
  ('cfo', 'CFO', 'Finanzas y proyecciones', '💰', '#10B981', 'claude-sonnet-4-6'),
  ('cs', 'CS', 'Clientes y soporte', '🤝', '#06B6D4', 'claude-sonnet-4-6'),
  ('ae', 'AE', 'Ventas y demos', '🚀', '#F97316', 'claude-sonnet-4-6'),
  ('coo', 'COO', 'Operaciones', '⚙️', '#6366F1', 'claude-sonnet-4-6')
on conflict (id) do nothing;

-- ============================================================
-- SEED DATA — Connectors
-- ============================================================
insert into public.connectors (name, display_name, status) values
  ('meta_ads', 'Meta Ads', 'disconnected'),
  ('linkedin', 'LinkedIn', 'disconnected'),
  ('gmail', 'Gmail', 'disconnected'),
  ('google_calendar', 'Google Calendar', 'disconnected'),
  ('stripe', 'Stripe', 'disconnected'),
  ('whatsapp', 'WhatsApp Business', 'disconnected'),
  ('telegram', 'Telegram', 'disconnected'),
  ('airtable', 'Airtable', 'disconnected')
on conflict (name) do nothing;

-- ============================================================
-- REALTIME — Enable for live dashboard
-- ============================================================
alter publication supabase_realtime add table agent_runs;
alter publication supabase_realtime add table notifications;
alter publication supabase_realtime add table projects;
